# Site settings
title: Synthesizing Concepts from Biology and Computer Science
email: dolsonem@msu.edu
description: >
  Workshop at Artificial Life XV on bringing together research on concepts that are
  studied in various isolated subfields of biology and computer science.
baseurl: "/scbcs"
url: "http://emilydolson.github.io"
fixedNav: 'true' # true or false
theme: purple # green, blue, orange, purple, grey
twitterUsername: emilyldolson
githubUsername: emilydolson
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
